### ISSUE TITLE
Client: evaluate solution

### ISSUE THREAD

**Issue by tracy2811** [IU-MAP/project-distributed-online-judge#29]
This is a task of US #13 
- [x] Run solution
- [x] Compare output
- [x] Update solution status, message

**Comment by KerimKochekov** [comment]
Implemented judging system for volunteer part in client side(shell script for running in linux OS). It downloads solution to user side, and downloads testdata of belonging solution if not exists locally. Later start judging for each input case and compare results with intendent output. If we encounter fail(or not same output with intendent testcase output) it terminates judge.
